# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/bahar/Term_Project_Final/Term_Project_Final/Term_Project_Final.runs/synth_1/Project_top_module.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 3
set_param xicom.use_bs_reader 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/bahar/Term_Project_Final/Term_Project_Final/Term_Project_Final.cache/wt [current_project]
set_property parent.project_path C:/Users/bahar/Term_Project_Final/Term_Project_Final/Term_Project_Final.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part_repo_paths {C:/Users/bahar/AppData/Roaming/Xilinx/Vivado/2024.1/xhub/board_store/xilinx_board_store} [current_project]
set_property board_part digilentinc.com:nexys-a7-100t:part0:1.2 [current_project]
set_property ip_output_repo c:/Users/bahar/Term_Project_Final/Term_Project_Final/Term_Project_Final.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_mem C:/Users/bahar/Term_Project_Final/Term_Project_Final/Term_Project_Final.srcs/sources_1/imports/HDL/Instructions.hex
read_verilog -library xil_defaultlib {
  C:/Users/bahar/Term_Project_Final/Term_Project_Final/Term_Project_Final.srcs/sources_1/imports/HDL/ALU.v
  C:/Users/bahar/Term_Project_Final/Term_Project_Final/Term_Project_Final.srcs/sources_1/imports/HDL/Adder.v
  C:/Users/bahar/Term_Project_Final/Term_Project_Final/Term_Project_Final.srcs/sources_1/imports/HDL/Controller.v
  C:/Users/bahar/Term_Project_Final/Term_Project_Final/Term_Project_Final.srcs/sources_1/imports/HDL/Datapath.v
  C:/Users/bahar/Term_Project_Final/Term_Project_Final/Term_Project_Final.srcs/sources_1/imports/HDL/Decoder_5to32.v
  C:/Users/bahar/Term_Project_Final/Term_Project_Final/Term_Project_Final.srcs/sources_1/imports/HDL/Extender.v
  C:/Users/bahar/Term_Project_Final/Term_Project_Final/Term_Project_Final.srcs/sources_1/imports/HDL/Extender_Load.v
  C:/Users/bahar/Term_Project_Final/Term_Project_Final/Term_Project_Final.srcs/sources_1/imports/HDL/MSSD.v
  C:/Users/bahar/Term_Project_Final/Term_Project_Final/Term_Project_Final.srcs/sources_1/imports/HDL/MUX_2to1.v
  C:/Users/bahar/Term_Project_Final/Term_Project_Final/Term_Project_Final.srcs/sources_1/imports/HDL/MUX_4to1.v
  C:/Users/bahar/Term_Project_Final/Term_Project_Final/Term_Project_Final.srcs/sources_1/imports/HDL/Memory_DATA.v
  C:/Users/bahar/Term_Project_Final/Term_Project_Final/Term_Project_Final.srcs/sources_1/imports/HDL/Memory_INST.v
  C:/Users/bahar/Term_Project_Final/Term_Project_Final/Term_Project_Final.srcs/sources_1/imports/HDL/Project_top_module_RISCV.v
  C:/Users/bahar/Term_Project_Final/Term_Project_Final/Term_Project_Final.srcs/sources_1/imports/HDL/Register_File.v
  C:/Users/bahar/Term_Project_Final/Term_Project_Final/Term_Project_Final.srcs/sources_1/imports/HDL/Register_reset.v
  C:/Users/bahar/Term_Project_Final/Term_Project_Final/Term_Project_Final.srcs/sources_1/imports/HDL/Register_rsten.v
  C:/Users/bahar/Term_Project_Final/Term_Project_Final/Term_Project_Final.srcs/sources_1/imports/HDL/SSD.v
  C:/Users/bahar/Term_Project_Final/Term_Project_Final/Term_Project_Final.srcs/sources_1/imports/HDL/UART_FIFO.v
  C:/Users/bahar/Term_Project_Final/Term_Project_Final/Term_Project_Final.srcs/sources_1/imports/HDL/UART_Peripheral.v
  C:/Users/bahar/Term_Project_Final/Term_Project_Final/Term_Project_Final.srcs/sources_1/imports/HDL/UART_RX.v
  C:/Users/bahar/Term_Project_Final/Term_Project_Final/Term_Project_Final.srcs/sources_1/imports/HDL/UART_TX.v
  C:/Users/bahar/Term_Project_Final/Term_Project_Final/Term_Project_Final.srcs/sources_1/imports/HDL/debouncer.v
  C:/Users/bahar/Term_Project_Final/Term_Project_Final/Term_Project_Final.srcs/sources_1/imports/HDL/Project_top_module.v
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/bahar/Term_Project_Final/Term_Project_Final/Term_Project_Final.srcs/constrs_1/imports/EE446/Nexys-A7-100T-Master.xdc
set_property used_in_implementation false [get_files C:/Users/bahar/Term_Project_Final/Term_Project_Final/Term_Project_Final.srcs/constrs_1/imports/EE446/Nexys-A7-100T-Master.xdc]

set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental C:/Users/bahar/Term_Project_Final/Term_Project_Final/Term_Project_Final.srcs/utils_1/imports/synth_1/Project_top_module.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top Project_top_module -part xc7a100tcsg324-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Project_top_module.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file Project_top_module_utilization_synth.rpt -pb Project_top_module_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
